from tkinter import *
root = Tk()

root.title('my totalizer')
root.geometry("500x700")
root.minsize(width=15, height=15)
root.wm_iconbitmap('qwe.ico')
root.config(background='#1A2130')

def click(event):
    global valuess
    text = event.widget.cget('text')
    print(text)
    if text == '=':
        if valuess.get().isdigit():
            value = int(valuess.get())
        else:
            value = eval(screen.get())
        valuess.set(value)
        screen.update()
    elif text == 'C':
        valuess.set("")
        screen.update()
    else:
        valuess.set(valuess.get() + text)
        screen.update()

valuess = StringVar()
valuess.set("")
screen = Entry(root, textvar=valuess, font='germand 25 bold', bg='#FFFAF0', fg='#1A2130')
screen.pack(ipadx=8, padx=10, pady=10)

f = Frame(root, bg='#1A2130')
b = Button(f, text='C', padx=48, pady=15, font='germand 25 bold', bg='#FF6F61', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='%', padx=15, pady=15, font='germand 25 bold', bg='#88B04B', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='/', padx=15, pady=15, font='germand 25 bold', bg='#88B04B', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root, bg='#1A2130')
b = Button(f, text='7', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='8', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='9', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='*', padx=15, pady=15, font='germand 25 bold', bg='#88B04B', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root, bg='#1A2130')
b = Button(f, text='4', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='5', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='6', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='-', padx=15, pady=15, font='germand 25 bold', bg='#88B04B', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root, bg='#1A2130')
b = Button(f, text='1', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='2', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='3', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='+', padx=15, pady=15, font='germand 25 bold', bg='#88B04B', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
f.pack()

f = Frame(root, bg='#1A2130')
b = Button(f, text='.', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='0', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='00', padx=15, pady=15, font='germand 25 bold', bg='#6B5B95', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
b = Button(f, text='=', padx=15, pady=15, font='germand 25 bold', bg='#FF6F61', fg='white')
b.pack(side='left', padx=5, pady=10)
b.bind('<Button-1>', click)
f.pack()

root.mainloop()
